Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-08, with the labels that each got.

#185 Set resources for multiple addons
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/metallb.yaml
  templates/opsportal.yaml
  templates/traefik-forward-auth.yaml
Labels: ready

#186 bump velero chart
  templates/velero.yaml
Labels: ready

#188 Convert to new addon repos
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/kibana.yaml
  templates/traefik-forward-auth.yaml
Labels: ready

#187 templates: bump prometheus and opsportal
  templates/opsportal.yaml
  templates/prometheus.yaml
Labels: ready

#189 Bump prometheus-operator to 5.10.6
  templates/prometheus.yaml
Labels: ready

#191 Scrape velero monitoring prom endpoint
  templates/prometheus.yaml
  templates/velero.yaml
Labels: ready

#194 [DCOS-56671] prometheus-adapter: set resources
  templates/prometheusadapter.yaml
Labels: ready

#195 traefik-auth-requires: add requires for traefik
  templates/traefik-forward-auth.yaml
Labels: ready

#196 dex-k8s-authorizator: add dex as requires
  templates/dex-k8s-authenticator.yaml
Labels: ready

#198 prometheusadapter: fix format
  templates/prometheusadapter.yaml
Labels: DoNoTMergeYet, ready

#201 Export and scrape Kibana metrics
  templates/kibana.yaml
  templates/prometheus.yaml
Labels: ready

#202 [chore] Remove CRDs
  README.md
  crds/kubeaddons_v1alpha1_addon.yaml
Labels: chore, ready

#204 Bump prometheus-operator to 5.10.9
  templates/prometheus.yaml
Labels: ready

#203 [bug] Remove ingress controller dep from dex-k8s-auth
  templates/dex-k8s-authenticator.yaml
Labels: bug, ready
