Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-07, with the labels that each got.

#65 prometheus: specify an additional scrape to collect containerd metrics
  templates/prometheus.yaml
Labels: ready

#66 enables ingress status update by Traefik
  templates/traefik.yaml
Labels: ready

#68 Add a template for the local volume provisioner
  templates/localvolumeprovisioner.yaml
Labels: ready

#70 templates/localvolumeprovisioner: bump chart version to 0.1.1
  templates/localvolumeprovisioner.yaml
Labels: ready

#63 dex
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/traefik.yaml
Labels: ready

#71 label generic capabilities
  templates/awsebscsidriverstorageclass.yaml
  templates/awsebscsidriverstorageclassdefault.yaml
  templates/awsstorageclass.yaml
  templates/awsstorageclassdefault.yaml
  templates/calico.yaml
  templates/localstorageclass.yaml
  templates/localstorageclassdefault.yaml
  templates/traefik.yaml
Labels: ready

#73 add name label for filtering
  templates/awsebscsidriver.yaml
  templates/awsebscsidriverstorageclass.yaml
  templates/awsebscsidriverstorageclassdefault.yaml
  templates/awsstorageclass.yaml
  templates/awsstorageclassdefault.yaml
  templates/calico.yaml
  templates/dashboard.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/localstorageclass.yaml
  templates/localstorageclassdefault.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik.yaml
  templates/velero.yaml
Labels: ready

#77 templates/dex: rename /dex-k8s-authenticator to /token endpoint
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
Labels: ready

#72 Add cloudProvider mapping
  templates/awsebscsidriver.yaml
  templates/awsebscsidriverstorageclass.yaml
  templates/awsebscsidriverstorageclassdefault.yaml
  templates/awsstorageclass.yaml
  templates/awsstorageclassdefault.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/localstorageclass.yaml
  templates/localstorageclassdefault.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/prometheus.yaml
Labels: ready

#75 Port storage addons to charts repo from kubeaddons-config
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/localpathprovisioner.yaml
Labels: ready

#79 make cloudProvider more extendable
  templates/awsebscsidriver.yaml
  templates/awsebscsidriverstorageclass.yaml
  templates/awsebscsidriverstorageclassdefault.yaml
  templates/awsstorageclass.yaml
  templates/awsstorageclassdefault.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/localstorageclass.yaml
  templates/localstorageclassdefault.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/prometheus.yaml
Labels: ready

#80 kommander: be a chart
  templates/kommander.yaml
Labels: ready

#81 templates/dex-k8s-authenticator: bump to hide oidc client secret from users
  templates/dex-k8s-authenticator.yaml
Labels: ready

#85 kommander: use available version
  templates/kommander.yaml
Labels: ready

#84 kommander required annotations
  templates/awsebscsidriver.yaml
  templates/awsebscsiprovisioner.yaml
  templates/calico.yaml
  templates/dashboard.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/localpathprovisioner.yaml
  templates/metallb.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik.yaml
Labels: ready

#87 fixing issues with crds
  templates/awsebscsidriver.yaml
  templates/awsebscsiprovisioner.yaml
  templates/calico.yaml
  templates/dashboard.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/localpathprovisioner.yaml
  templates/metallb.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik.yaml
Labels: ready

#78 Add annotations pointing to documentation
  templates/dashboard.yaml
  templates/kibana.yaml
  templates/prometheus.yaml
  templates/traefik.yaml
Labels: ready

#88 changed crd namespace for kommander
  templates/kommander.yaml
Labels: ready

#83 templates: remove old storageclass based templates
  templates/awsebscsidriverstorageclass.yaml
  templates/awsebscsidriverstorageclassdefault.yaml
  templates/awsstorageclass.yaml
  templates/awsstorageclassdefault.yaml
  templates/localstorageclass.yaml
  templates/localstorageclassdefault.yaml
Labels: ready

#90 templates/dex: bump dex to include new theme
  templates/dex.yaml
Labels: ready

#86 calico: remove Calico addon
  templates/calico.yaml
Labels: ready

#91 versions of prometheus operator tools
  templates/awsebscsidriver.yaml
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/dashboard.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/localpathprovisioner.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik.yaml
Labels: ready

#74 Add requirement matching
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/localvolumeprovisioner.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik.yaml
  templates/velero.yaml
Labels: ready

#94 ops portal version is fixed
  templates/opsportal.yaml
Labels: ready

#96 dashboards: update localvolumeprovisioner dashboard
  dashboards/localvolumeprovisioner.yaml
Labels: ready

#76 Ops Portal authentication and authorization
  templates/dex.yaml
  templates/opsportal.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
Labels: ready

#99 Change rules to authenticate only Ops Portal
  templates/traefik-forward-auth.yaml
Labels: ready

#97 Convert Velero To Helm Chart Implementation
  templates/velero.yaml
Labels: ready

#100 Disable Velero ServiceMonitor
  templates/velero.yaml
Labels: ready

#102 Use ingress record added to the kommander template
  templates/kommander.yaml
Labels: ready

#95 Added a dashboard for local volume provisioner.
  dashboards/localvolumeprovisioner.yaml
Labels: ready

#110 Convert Velero to Chart
  templates/velero.yaml
Labels: LetMeMerge, blocked, ready

#98 manifest to charts for awsebscsidriver and opsportal
  templates/awsebscsidriver.yaml
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/dex.yaml
  templates/opsportal.yaml
Labels: ready

#101 Dashboards for ES, Fluent Bit, Grafana, Prometheus, Traefik
  dashboards/elasticsearchdashboard.yaml
  dashboards/fluentbitdashboard.yaml
  dashboards/grafanadashboard.yaml
  dashboards/prometheusoverview.yaml
  dashboards/traefikdashboard.yaml
  templates/prometheus.yaml
Labels: ready

#111 fixing enabled flag
  templates/dex.yaml
Labels: ready

#112 dex is enabled in this PR
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
Labels: ready

#113 pick a domain
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/localpathprovisioner.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/traefik.yaml
Labels: ready

#114 revert opsportal to manifest
  templates/opsportal.yaml
Labels: ready

#116 Add sidecar container for spinning up Kibana index
  templates/kibana.yaml
Labels: ready

#115 fixes cloudProvider values found in specs
  templates/localpathprovisioner.yaml
  templates/localvolumeprovisioner.yaml
  templates/prometheusadapter.yaml
  templates/velero.yaml
Labels: ready

#118 Remove deprecated opsportal
  templates/opsportal.yaml
Labels: ready

#119 Add initcontainer to traefik-forward-auth
  templates/traefik-forward-auth.yaml
Labels: ready

#120 updated chart versions consistent with charts repo
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/kommander.yaml
  templates/localvolumeprovisioner.yaml
Labels: ready

#121 updated chart versions and updated awsebsprovisioner
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/kommander.yaml
Labels: ready

#108 kommander: bump chart version
  templates/kommander.yaml
Labels: ready

#122 templates/dex: add initcontainer configuration
  templates/dex.yaml
Labels: ready

#129 Prepare to replace traefik forward auth with ingress annotations
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
Labels: ready

#130 dashboards: add a dashboard to display per-node volume space usage
  dashboards/localvolumeusage.yaml
Labels: ready

#131 templates: fix min supported version
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/dashboard.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/localpathprovisioner.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
  templates/velero.yaml
Labels: ready

#132 konvoy-ui: don't attempt to create the CRD
  templates/konvoy-ui.yaml
Labels: ready

#133 bump ops portal version
  templates/opsportal.yaml
Labels: ready

#139 kibana: bump sidecar version to support envs
  templates/kibana.yaml
Labels: DoNoTMergeYet

#140 dashboards: fix prometheus datasource of storage dashboards
  dashboards/localvolumeprovisioner.yaml
  dashboards/localvolumeusage.yaml
Labels: ready

#144 Remove redundant rules
  templates/traefik-forward-auth.yaml
Labels: ready

#146 Utilize Velero 2.1.2 from mesosphere/charts for minio backend options
  templates/velero.yaml
Labels: ready

#147 Export kommander metrics to Prometheus
  templates/kommander.yaml
  templates/konvoy-ui.yaml
  templates/prometheus.yaml
Labels: ready

#153 templates: bump AWS EBS provisioner versions
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
Labels: ready

#142 [dex-k8s-authenticator]: avoid using subPath for the secrets
  templates/dex-k8s-authenticator.yaml
Labels: ready

#151 Add polling intervals for konvoy ui
  templates/konvoy-ui.yaml
Labels: ready

#150 remove dashboards and rules for prometheus
  dashboards/apiserver.yaml
  dashboards/controlmanager.yaml
  dashboards/elasticsearchdashboard.yaml
  dashboards/fluentbitdashboard.yaml
  dashboards/grafanadashboard.yaml
  dashboards/kubelet.yaml
  dashboards/localvolumeprovisioner.yaml
  dashboards/localvolumeusage.yaml
  dashboards/prometheusoverview.yaml
  dashboards/scheduler.yaml
  dashboards/traefikdashboard.yaml
  prometheus-rules/etcd-rules.yaml
  templates/prometheus.yaml
Labels: ready

#157 Update DKA and add initContainer setup
  templates/dex-k8s-authenticator.yaml
Labels: blocked, ready

#156 tfa: update to version with hooks
  templates/traefik-forward-auth.yaml
Labels: blocked, ready

#158 chart version bump for kommander
  templates/kommander.yaml
  templates/konvoy-ui.yaml
Labels: ready

#159 [chore] allow the creation of the crd
  templates/kommander.yaml
  templates/konvoy-ui.yaml
Labels: ready

#161 localvolumeprovisioner: bump the version to the latest
  templates/localvolumeprovisioner.yaml
Labels: ready

#155 opsportal: bump chart version
  templates/opsportal.yaml
Labels: ready

#160 templates/dex-k8s-authenticator: bump container
  templates/dex-k8s-authenticator.yaml
Labels: DoNoTMergeYet, ready

#162 awsebscsiprovisioner: bump the version
  templates/awsebscsiprovisioner.yaml
Labels: ready

#163 kibana: fix extraContainers
  templates/kibana.yaml
Labels: ready

#167 grafana: fix CPUThrottlingHigh issues
  templates/prometheus.yaml
Labels: ready

#170 awsebscsiprovisioner: bump chart version
  templates/awsebscsiprovisioner.yaml
Labels: ready

#169 Update prometheus docs link
  templates/prometheus.yaml
Labels: ready

#145 dex: bump dex container and set d2iq theme
  templates/dex.yaml
Labels: ready

#173 dex-k8s-authenticator: add missing ConfigMap value
  templates/dex-k8s-authenticator.yaml
Labels: ready

#174 Tag extrasteps to v0.0.2
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/kibana.yaml
  templates/traefik-forward-auth.yaml
Labels: ready

#175 localvolumeprovisioner: change the namespace to kube-system
  templates/localvolumeprovisioner.yaml
Labels: ready

#177 Update chart versions for new docker images
  templates/opsportal.yaml
  templates/traefik-forward-auth.yaml
  templates/velero.yaml
Labels: ready

#178 opsportal: version with image fix
  templates/opsportal.yaml
Labels: ready

#179 localvolumeprovisioner: bump version
  templates/localvolumeprovisioner.yaml
Labels: ready

#172 Expose calico metrics
  templates/prometheus.yaml
Labels: ready

#180 Update dex version to latest image tag
  templates/dex.yaml
Labels: ready

#182 Bump prometheus-operator chart to 5.10.4
  templates/prometheus.yaml
Labels: ready

#183 Remove local path provisioner
  templates/localpathprovisioner.yaml
Labels: LetMeMerge, ready

#181 opsportal: test my chart
  templates/konvoy-ui.yaml
  templates/opsportal.yaml
Labels: ready

#184 Velero
  templates/velero.yaml
Labels: LetMeMerge, ready
