Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-12, with the labels that each got.

#343 [ci] Add elastic test coverage
  test/addons_test.go
  test/go.mod
  test/go.sum
Labels: ready

#354 templates: addons adjust the resource limits
  templates/dashboard.yaml
  templates/elasticsearch.yaml
  templates/gatekeeper.yaml
  templates/traefik.yaml
Labels: ready

#352 templates: bump the initializer version to latest
  templates/dex-k8s-authenticator.yaml
  templates/kibana.yaml
  templates/kube-oidc-proxy.yaml
  templates/prometheus.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
Labels: chore, ready

#353 chore: bump kommander/opsportal charts
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#341 Dashboard authroization
  templates/dashboard.yaml
  templates/opsportal.yaml
  templates/traefik-forward-auth.yaml
Labels: ready

#358 chore: bump kommander chart
  templates/kommander.yaml
Labels: ready

#357 prometheus: kube-state-metrics
  templates/prometheus.yaml
Labels: ready

#362 chore: bump kommander chart to 0.2.26
  templates/kommander.yaml
Labels: ready

#361 chore: bump kommander chart to 0.2.26
  templates/kommander.yaml
Labels: ready

#364 prometheus: bump kube state metrics
  templates/prometheus.yaml
Labels: ready

#359 dispatch: update chart version
  templates/dispatch.yaml
Labels: LetMeMerge, ready

#365 bump tfa to 1.0.6
  templates/traefik-forward-auth.yaml
Labels: ready

#367 chore: bump kommander chart to 0.2.27
  templates/kommander.yaml
Labels: ready

#366 chore: bump kommander chart to 0.2.27
  templates/kommander.yaml
Labels: ready

#369 chore: bump kommander and ops portal charts
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#350 Bumped the Nvidia chart version to support GPU metrics.
  templates/nvidia.yaml
  templates/prometheus.yaml
Labels: ready

#368 Upgrade prometheus-operator
  templates/prometheus.yaml
Labels: ready

#370 put dashboard in kubeaddons
  templates/dashboard.yaml
Labels: DoNoTMergeYet, ready

#371 [fluent-bit] update with audit log values.
  templates/fluentbit.yaml
Labels: ready

#372 [fluent-bit] change to using json parser for audit logs
  templates/fluentbit.yaml
Labels: ready

#373 [fluent-bit] Create an audit parser
  templates/fluentbit.yaml
Labels: wip

#374 apply upgrade strategy
  templates/dashboard.yaml
Labels: ready

#376 kommander: bump chart to 0.2.29
  templates/kommander.yaml
Labels: blocked, ready

#377 readme: update deprecation language
  README.md
Labels: ready
