Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-11, with the labels that each got.

#300 traefik: bump chart, catalog and initializer version
  templates/traefik.yaml
Labels: chore, ready

#301 dex-k8s-authenticator: bump versions for distributed auth
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
Labels: ready

#303 dex-k8s-authenticator: reload pod on config change
  templates/dex-k8s-authenticator.yaml
Labels: ready

#304 kommander: update chart version to 0.1.52
  templates/kommander.yaml
Labels: ready

#308 Bump Nvidia chart version and make nvidia driver image tag configurable.
  templates/nvidia.yaml
Labels: ready

#305 kommander: update chart version to 0.1.53
  templates/kommander.yaml
Labels: ready

#309 Add priority to ingress
  templates/traefik-forward-auth.yaml
Labels: ready

#311 Bump kubeaddons-addon-initializer for dex
  templates/dex.yaml
Labels: ready

#310 Bump kommander chart version
  templates/kommander.yaml
Labels: ready

#315 [kommander] update kommander chart version
  templates/kommander.yaml
Labels: ready

#318 chore: bump kommander and ops portal chart versions
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#320 kommander: Reload karma configmap on edit
  templates/kommander.yaml
Labels: ready

#314 Azure provider support
  templates/azuredisk-csi-driver.yaml
  templates/azurediskprovisioner.yaml
  templates/cert-manager.yaml
  templates/dashboard.yaml
  templates/defaultstorageclass-protection.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/external-dns.yaml
  templates/fluentbit.yaml
  templates/gatekeeper.yaml
  templates/istio.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/konvoyconfig.yaml
  templates/kube-oidc-proxy.yaml
  templates/kudo.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/nvidia.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/velero.yaml
Labels: ready

#319 grafana/kibana: use a sidecar container for plugins
  templates/kibana.yaml
  templates/prometheus.yaml
Labels: ready

#323 Add Flagger
  templates/flagger.yaml
  templates/istio.yaml
Labels: ready

#324 kommander: bump version
  templates/kommander.yaml
Labels: ready

#325 Revert "Add Flagger"
  templates/flagger.yaml
  templates/istio.yaml
Labels: ready

#326 templates: fix docker for the local volume provisioner
  templates/localvolumeprovisioner.yaml
Labels: bug, ready

#328 dispatch: add initial kubeaddon
  templates/dispatch.yaml
Labels: ready

#330 kommander: version bump and configure image version of kubeaddons
  templates/kommander.yaml
Labels: LetMeMerge

#331 feat(kommander): Update defaulting kubeaddons-configs values
  templates/kommander.yaml
Labels: ready

#333 kommander: version bump
  templates/kommander.yaml
Labels: ready

#332 chore: bump kommander/opsportal chart versions
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#334 opsportal: fix via chart version bump
  templates/opsportal.yaml
Labels: ready

#335 kommander: bump kcl
  templates/kommander.yaml
Labels: ready

#336 kommander: include catalog in kommander addon
  templates/kommander.yaml
Labels: LetMeMerge, ready

#338 Revert "chore: bump kommander/opsportal charts for new image tag 1.150.5"
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#339 chore(kommander): Upgrade kubeaddons-configs mapping to kommander-beta6
  templates/kommander.yaml
Labels: ready

#340 chore: bump kommander/opsportal charts for image update 1.150.12
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: LetMeMerge, ready

#342 [ci] Addon test framework
  test/addons_test.go
  test/go.mod
  test/go.sum
Labels: ready

#344 chore: bump addons versions to support Kubernetes v1.16
  templates/dashboard.yaml
  templates/dispatch.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/metallb.yaml
  templates/prometheus.yaml
  templates/velero.yaml
Labels: DoNoTMergeYet

#346 flagger: add azure provider
  templates/flagger.yaml
Labels: ready

#347 kommander: Bump to v0.2.19
  templates/kommander.yaml
Labels: ready

#345 awscsi: bump ebs csi
  templates/awsebscsiprovisioner.yaml
Labels: LetMeMerge, ready

#348 Update outdated appversion annotations
  templates/dex.yaml
  templates/dispatch.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/konvoyconfig.yaml
  templates/metallb.yaml
  templates/traefik.yaml
Labels: ready

#349 awscsi: fix bug in the chart version
  templates/awsebscsiprovisioner.yaml
Labels: bug

#351 awsebs: bump chart version
  templates/awsebsprovisioner.yaml
Labels: ready
