Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-10, with the labels that each got.

#227 Adds kube-oidc-proxy config
  templates/konvoyconfig.yaml
  templates/kube-oidc-proxy.yaml
Labels: ready

#233 stable/1.15.4: bump certmanager version
  templates/cert-manager.yaml
Labels: ready

#231 bump kommander version to 0.1.26
  templates/kommander.yaml
Labels: ready

#234 cert-manager: bump version
  templates/cert-manager.yaml
Labels: ready

#229 dex: requires cert-manager
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
Labels: ready

#237 Update to traefik-forward-auth 1.0.4
  templates/traefik-forward-auth.yaml
Labels: ready

#238 Update to traefik-forward-auth 1.0.4
  templates/traefik-forward-auth.yaml
Labels: ready

#246 [kommander] bump chart version and include KCL values.
  templates/kommander.yaml
Labels: DoNoTMergeYet, wip

#212 nvidia: Added nvidia kubeaddon config
  templates/nvidia.yaml
Labels: ready

#249 velero: bump version to support minio service annotations
  templates/velero.yaml
Labels: ready

#243 Expose Dex via Traefik URL
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/kube-oidc-proxy.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
Labels: ready

#254 Bump kube-oidc-proxy chart version
  templates/kube-oidc-proxy.yaml
Labels: ready

#258 Remove namespace from spec on all addons
  templates/awsebscsiprovisioner.yaml
  templates/cert-manager.yaml
  templates/dashboard.yaml
  templates/kommander.yaml
  templates/localvolumeprovisioner.yaml
  templates/nvidia.yaml
  templates/velero.yaml
Labels: chore, ready

#256 templates: update nvidia properties
  templates/nvidia.yaml
Labels: ready

#260 [kommander,opsportal] Kommander staging
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#264 chore: bump opsportal and kommander to latest charts
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#259 Bump chart version
  templates/dex-k8s-authenticator.yaml
Labels: blocked, ready

#222 Remove Kommander DSC Requirement
  templates/kommander.yaml
Labels: bug, ready

#225 Upgrade prometheus-operator
  templates/prometheus.yaml
Labels: LetMeMerge, ready

#267 traefik: bump version
  templates/traefik.yaml
Labels: ready

#266 DCOS-59577 Add gatekeeper to kubeaddon configs
  templates/gatekeeper.yaml
Labels: needs_signed_commits, ready

#269 Use Prometheus v2.9.2
  templates/prometheus.yaml
Labels: ready

#272 gatekeeper: temporary disable it
  templates/gatekeeper.yaml
Labels: ready

#271 dex: bump to use dex-controller v0.2.0
  templates/dex.yaml
Labels: ready

#274 gatekeeper: enable it by default
  templates/gatekeeper.yaml
Labels: ready

#270 default storage class addon and requirements
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/defaultstorageclass.yaml
  templates/localvolumeprovisioner.yaml
Labels: ready

#275 kommander: Bump to chart version 0.1.37
  templates/kommander.yaml
Labels: ready

#282 kube-oidc-proxy: add groupsPrefix
  templates/kube-oidc-proxy.yaml
Labels: ready

#281 Add service port for Thanos gRPC
  templates/prometheus.yaml
Labels: ready

#284 Add Catalog annotations to addons
  CONTRIBUTING.md
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/cert-manager.yaml
  templates/dashboard.yaml
  templates/defaultstorageclass.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/gatekeeper.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/konvoyconfig.yaml
  templates/kube-oidc-proxy.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/nvidia.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
  templates/velero.yaml
Labels: ready

#283 dashboard/prometheus: use gcr.io/google_containers instead of k8s.gcr.io
  templates/dashboard.yaml
  templates/prometheus.yaml
Labels: ready

#277 rename defaultstorageclass.yaml to defaultstorageclass-protection.yaml
  templates/defaultstorageclass-protection.yaml
Labels: ready

#285 dashboard/prometheus: use gcr.io/google_containers instead of k8s.gcr.io
  templates/dashboard.yaml
  templates/prometheus.yaml
Labels: ready

#286 add kudo addon
  templates/kudo.yaml
Labels: ready

#289 Add cloudProvider options in addon spec for dashboard
  templates/dashboard.yaml
Labels: ready

#280 convert to v1beta1 clusteraddons
  crds/kubeaddons_v1alpha1_addon.yaml
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/cert-manager.yaml
  templates/dashboard.yaml
  templates/defaultstorageclass-protection.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/gatekeeper.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/konvoyconfig.yaml
  templates/kube-oidc-proxy.yaml
  templates/kudo.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/nvidia.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
  templates/velero.yaml
Labels: ready

#290 kommander: bump kommander version to v0.1.41
  templates/kommander.yaml
Labels: ready

#268 prometheus: Set externalLabels cluster label to kube-system ns uid
  templates/kibana.yaml
  templates/prometheus.yaml
Labels: ready

#292 update opsportal and kommander chart versions
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#293 reloader: add new addon
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/kube-oidc-proxy.yaml
  templates/reloader.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
Labels: ready

#295 [prometheus] Upgrade thanos sidecar, scrape thanos query metrics
  templates/prometheus.yaml
Labels: ready

#294 integrating istio as an addon on konvoy
  templates/istio.yaml
Labels: ready

#297 grafana/kibana: use a sidecar container for plugins
  templates/kibana.yaml
  templates/prometheus.yaml
Labels: ready
