Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-05, with the labels that each got.

#3 resources: set limits to the resource usage of the addons
  templates/dashboard.yaml
  templates/elasticsearch.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/prometheus.yaml
  templates/traefik.yaml
Labels: enhancement, paused, ready

#7 Add AWS EBS CSI Driver
  templates/awsebscsidriver.yaml
Labels: ready

#10 traefik: increase the cpu limits
  templates/traefik.yaml
Labels: ready

#11 grafana: disable AppArmor PSP
  templates/prometheus.yaml
Labels: paused

#14 calico: add custom template
  templates/calico.yaml
Labels: ready

#15 added templates for opsportal and localstorages
  templates/opsportal.yaml
  templates/storageclass_awscsidriver.yaml
  templates/storageclass_awsebs.yaml
  templates/storageclass_default_awscsidriver.yaml
  templates/storageclass_default_awsebs.yaml
  templates/storageclass_default_localpath.yaml
  templates/storageclass_localpath.yaml
Labels: wip

#24 [fix] opsportal deployment component needs to be separated out.
  templates/opsportal.yaml
Labels: ready

#25 prometheus: use a PVC instead of an emptyDir
  templates/prometheus.yaml
Labels: ready

#28 fix: correct the name of spec of a manifest
  templates/storageclass_awscsidriver.yaml
  templates/storageclass_default_awscsidriver.yaml
Labels: ready

#26 elasticsearch: add exporter for prometheus
  templates/elasticsearchexporter.yaml
Labels: ready

#22 calico: use default namespace
  templates/calico.yaml
Labels: ready

#16 elasticsearch: increase settings
  templates/elasticsearch.yaml
Labels: ready

#30 Improve Traefik Fault Tolerance
  templates/traefik.yaml
Labels: ready

#31 Add Velero
  templates/velero.yaml
Labels: ready

#32 [DCOS-52112] enabled metrics capturing for etcd assuming a secret exists
  templates/prometheus.yaml
Labels: ready
