Repository mesosphere/kubeaddons-configs, pull requests merged in 2019-09, with the labels that each got.

#171 templates: bump 'localvolumeprovisioner'
  templates/localvolumeprovisioner.yaml
Labels: LetMeMerge, blocked, ready

#205 prometheusadapter: fix empty node metrics
  templates/prometheusadapter.yaml
Labels: bug, ready

#206 Add CODEOWNERS
  CODEOWNERS
Labels: ready

#200 Expose keepalived metrics
  templates/prometheus.yaml
Labels: ready

#208 templates: bump 'localvolumeprovisioner'
  templates/localvolumeprovisioner.yaml
Labels: ready

#209 use cloudProvider values
  templates/awsebsprovisioner.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
Labels: ready

#213 updated chart version of kommander
  templates/kommander.yaml
Labels: ready

#214 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: ready

#216 Bump alertmanager version to v0.17.0
  templates/prometheus.yaml
Labels: ready

#217 Enable Thanos sidecar
  templates/prometheus.yaml
Labels: ready

#219 Add helm values yaml metadata to some addons
  templates/awsebscsiprovisioner.yaml
  templates/awsebsprovisioner.yaml
  templates/cert-manager.yaml
  templates/dashboard.yaml
  templates/dex-k8s-authenticator.yaml
  templates/dex.yaml
  templates/elasticsearch.yaml
  templates/elasticsearchexporter.yaml
  templates/fluentbit.yaml
  templates/kibana.yaml
  templates/kommander.yaml
  templates/localvolumeprovisioner.yaml
  templates/metallb.yaml
  templates/opsportal.yaml
  templates/prometheus.yaml
  templates/prometheusadapter.yaml
  templates/traefik-forward-auth.yaml
  templates/traefik.yaml
  templates/velero.yaml
Labels: ready

#220 awsebscsiprovisioner: bump to 0.3.1
  templates/awsebscsiprovisioner.yaml
Labels: ready

#221 [fix] update kommander and opsportal charts
  templates/kommander.yaml
  templates/opsportal.yaml
Labels: ready

#223 Adding konvoyconfig
  templates/konvoyconfig.yaml
Labels: ready

#224 Update traefik certificate with load balancer address
  templates/traefik.yaml
Labels: ready

#226 cert-manager: bump version
  templates/cert-manager.yaml
Labels: ready

#228 dex: bump version of kubeaddons-addon-initial and dex chart
  templates/dex.yaml
Labels: ready

#230 bump kommander version to 0.1.26
  templates/kommander.yaml
Labels: ready
